### PR TITLE
Why did you delete the languages?

### PR DESCRIPTION
**Pull request by montlikadani**
As in the title, why did you do it?
If something new or something else is done I will do it, because it also informs me.

### CODE REVIEW

**Comment by Plajer** [comment]
I won't support locales I can't handle myself.

I won't spam you with DM's to make an update for your locale in the future.

**Comment by montlikadani** [comment]
There is no need to handle what I or others put in, because we will do it, no matter if I miss the string I will do it too.

**Comment by Plajer** [comment]
I mean I support only locales I'm able to translate instantly when I want.

**Comment by montlikadani** [comment]
I will tell you that if this plugin is so famous and many will use it even among Hungarians, it would be worthwhile to accept this PR because I will use it soon and my players have to use the Hungarian language so they can use it.

As I said, it is not necessary to add strings because I'm looking at what's up to 2 days a day.

**Comment by Plajer** [comment]
Okay, I'll keep this locale for now, but before 3.0.0 final release there will be many changes in messages.

**Comment by montlikadani** [comment]
No problem, I'll look at the commit and I'll update it.

**Pull request merged**
